import { copyFile, mkdir, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { randomUUID } from 'node:crypto';
import type { Product } from '@helm/shared';
import { specBranchName, planBranchName } from '@helm/shared';
import { parseGitHubRepoUrl } from './fetch-product-context.js';
import {
  buildAuthenticatedUrl,
  sanitizeToken,
  defaultRunGit,
  defaultRunGh,
  type RunGit,
  type RunGh,
} from './git-helpers.js';

// ── Types ─────────────────────────────────────────────────────────────────────

export type PublishSpecOpts = {
  externalId: string;
  product: Product;
  /** Absolute path to specs/{externalId}.md in the workdir. */
  specPath: string;
  /** GitHub personal access token (repo scope). */
  githubToken: string;
};

export type PublishSpecResult = {
  prUrl: string;
};

export type PublishPlanOpts = {
  externalId: string;
  product: Product;
  /** Absolute path to plans/{externalId}.md in the workdir. */
  planPath: string;
  /** GitHub personal access token (repo scope). */
  githubToken: string;
};

export type PublishPlanResult = {
  prUrl: string;
};

/** Supported artifact kinds — determines branch, directory, and PR content. */
export type ArtifactKind = 'spec' | 'plan';

export type PublishArtifactOpts = {
  externalId: string;
  product: Product;
  /** Absolute path to the artifact file in the workdir. */
  artifactPath: string;
  /** GitHub personal access token (repo scope). */
  githubToken: string;
  /** Controls branch name, destination directory, and PR copy. */
  kind: ArtifactKind;
};

export type PublishArtifactResult = {
  prUrl: string;
};

// ── Re-exports for backward compatibility ─────────────────────────────────────
// RunGit and RunGh are imported by the dispatcher and tests via spec-publisher.
// They now live in git-helpers.ts but are re-exported here so existing import
// paths continue to work without changes.
export type { RunGit, RunGh } from './git-helpers.js';
export { defaultRunGit, defaultRunGh } from './git-helpers.js';

// ── Kind-specific configuration ───────────────────────────────────────────────

type ArtifactConfig = {
  readonly branchNameFn: (id: string) => string;
  readonly destSubDir: string;
  readonly commitMessage: (id: string) => string;
  readonly prTitle: (id: string) => string;
  readonly prBody: (id: string, slug: string) => string;
  readonly errorTag: string;
};

const ARTIFACT_CONFIG: Record<ArtifactKind, ArtifactConfig> = {
  spec: {
    branchNameFn: specBranchName,
    destSubDir: 'specs',
    commitMessage: (id) => `docs(spec): add spec for ${id}`,
    prTitle: (id) => `docs(spec): add spec for ${id}`,
    prBody: (id, slug) =>
      `Spec generated by Helm for item \`${id}\` in product \`${slug}\`.\n\nReview and merge to advance the item to **spec-ready**.`,
    errorTag: '[spec-publisher]',
  },
  plan: {
    branchNameFn: planBranchName,
    destSubDir: 'plans',
    commitMessage: (id) => `docs(plan): add plan for ${id}`,
    prTitle: (id) => `docs(plan): add plan for ${id}`,
    prBody: (id, slug) =>
      `Plan generated by Helm for item \`${id}\` in product \`${slug}\`.\n\nReview and merge to advance the item to **plan-ready**.`,
    errorTag: '[plan-publisher]',
  },
};

// ── Generic core ──────────────────────────────────────────────────────────────

/**
 * Publishes an artifact file (spec or plan) to the product's knowledge repo as a PR.
 *
 * **Isolation**: each call clones the knowledge repo into a fresh temporary
 * directory (under `os.tmpdir()`), performs all git operations there, and
 * removes the directory in a `finally` block.  This guarantees that two
 * concurrent publishes — even for the same product — never share a checkout
 * and cannot interleave git operations or corrupt each other's branches.
 *
 * Idempotency: if the artifact branch already has an open PR, the branch is
 * updated (force-pushed) and the existing PR URL is returned — no duplicates.
 *
 * @param opts      Publish options including product config, artifact path, token, and kind.
 * @param runGit    Injectable git runner (defaults to git via execFile).
 * @param runGh     Injectable gh runner (defaults to gh via execFile).
 */
export async function publishArtifactToPR(
  opts: PublishArtifactOpts,
  runGit: RunGit = defaultRunGit,
  runGh: RunGh = defaultRunGh,
): Promise<PublishArtifactResult> {
  const { externalId, product, artifactPath, githubToken, kind } = opts;
  const cfg = ARTIFACT_CONFIG[kind];

  // The (?!\.) lookahead rejects dot-segment values (`.`, `..`, `.hidden`, …)
  // in addition to the character-class restriction, preventing path traversal.
  const EXTERNAL_ID_SAFE = /^(?!\.)[A-Za-z0-9._-]+$/;
  if (!EXTERNAL_ID_SAFE.test(externalId)) {
    throw new Error(`${cfg.errorTag} Invalid externalId: "${externalId}"`);
  }

  const knowledgeRepo = product.knowledge_repo;
  const defaultBranch = knowledgeRepo.default_branch;
  const branchName = cfg.branchNameFn(externalId);

  const parsed = parseGitHubRepoUrl(knowledgeRepo.url);
  if (!parsed) {
    throw new Error(`${cfg.errorTag} Cannot parse knowledge repo URL: ${knowledgeRepo.url}`);
  }
  const { owner, repo } = parsed;

  // SSH-format knowledge repo URLs (git@github.com:org/repo or ssh://...) are
  // not supported for token-based authentication.  Fail early with a clear
  // message rather than silently falling through to a confusing auth error.
  if (knowledgeRepo.url.startsWith('git@') || knowledgeRepo.url.startsWith('ssh://')) {
    throw new Error(
      `${cfg.errorTag} SSH knowledge repo URLs are not supported for token-based auth. ` +
        `Use an HTTPS URL (https://github.com/${owner}/${repo}) instead.`,
    );
  }

  // Build the authenticated clone URL once.  The token is embedded as basic-auth
  // credentials so that `git clone` works with all git versions without requiring
  // GIT_CONFIG env var support (added in Git 2.31).  The `origin` remote inside
  // the resulting clone inherits this URL, so `git push origin` is authenticated
  // without any additional configuration.
  //
  // ⚠ Never log `authenticatedUrl`.  Always use `knowledgeRepo.url` (the plain
  //   URL) in error text, and pass raw git error strings through `sanitizeToken`.
  const authenticatedUrl = buildAuthenticatedUrl(owner, repo, githubToken);

  // Each publish gets its own isolated working directory so that concurrent
  // publishes for the same product do not share a checkout and cannot interleave
  // git operations (checkout, add, commit, push).  The directory is always
  // removed in the finally block — whether the publish succeeds or fails.
  const workDir = join(tmpdir(), `helm-publish-${externalId}-${randomUUID()}`);
  await mkdir(workDir, { recursive: true });

  try {
    // ── Step 1: Clone knowledge repo to isolated workdir ────────────────────
    // Use the authenticated URL so git can access private repos.  The plain URL
    // (without credentials) is used in the error message.
    try {
      await runGit(['clone', authenticatedUrl, workDir], { cwd: tmpdir() });
    } catch (err) {
      const raw = err instanceof Error ? err.message : String(err);
      throw new Error(
        `${cfg.errorTag} Failed to clone knowledge repo (${knowledgeRepo.url}): ${sanitizeToken(raw, githubToken)}`,
      );
    }

    // ── Step 2: Create or reset branch from default branch ──────────────────
    try {
      // -B creates the branch if absent, or resets it to HEAD if it already exists.
      await runGit(['checkout', '-B', branchName, `origin/${defaultBranch}`], {
        cwd: workDir,
      });
    } catch (err) {
      const raw = err instanceof Error ? err.message : String(err);
      throw new Error(
        `${cfg.errorTag} Failed to create branch '${branchName}': ${sanitizeToken(raw, githubToken)}`,
      );
    }

    // ── Step 3: Copy artifact into knowledge repo ────────────────────────────
    const destDir = join(workDir, cfg.destSubDir);
    const destPath = join(destDir, `${externalId}.md`);
    try {
      await mkdir(destDir, { recursive: true });
      await copyFile(artifactPath, destPath);
    } catch (err) {
      const raw = err instanceof Error ? err.message : String(err);
      throw new Error(
        `${cfg.errorTag} Failed to copy ${kind} file: ${sanitizeToken(raw, githubToken)}`,
      );
    }

    // ── Step 4: Commit ───────────────────────────────────────────────────────
    const gitEnv: NodeJS.ProcessEnv = {
      GIT_AUTHOR_NAME: 'helm-bot',
      GIT_AUTHOR_EMAIL: 'helm-bot@users.noreply.github.com',
      GIT_COMMITTER_NAME: 'helm-bot',
      GIT_COMMITTER_EMAIL: 'helm-bot@users.noreply.github.com',
    };
    try {
      await runGit(['add', join(cfg.destSubDir, `${externalId}.md`)], { cwd: workDir });
      await runGit(['commit', '--allow-empty', '-m', cfg.commitMessage(externalId)], {
        cwd: workDir,
        env: gitEnv,
      });
    } catch (err) {
      const raw = err instanceof Error ? err.message : String(err);
      throw new Error(
        `${cfg.errorTag} Failed to commit ${kind}: ${sanitizeToken(raw, githubToken)}`,
      );
    }

    // ── Step 5: Push branch ──────────────────────────────────────────────────
    // The `origin` remote already holds the authenticated URL from the clone step,
    // so no extra credentials are needed here.
    try {
      await runGit(['push', 'origin', `${branchName}:${branchName}`, '--force'], {
        cwd: workDir,
      });
    } catch (err) {
      const raw = err instanceof Error ? err.message : String(err);
      throw new Error(
        `${cfg.errorTag} Failed to push branch '${branchName}': ${sanitizeToken(raw, githubToken)}`,
      );
    }

    // ── Step 6: Open PR (idempotent) ─────────────────────────────────────────
    const ghEnv: NodeJS.ProcessEnv = { GITHUB_TOKEN: githubToken };

    // Check for an existing open PR before creating a new one.
    let existingPrUrl: string | null = null;
    try {
      const listOut = await runGh(
        [
          'pr',
          'list',
          '--repo',
          `${owner}/${repo}`,
          '--head',
          branchName,
          '--state',
          'open',
          '--json',
          'url',
        ],
        { env: ghEnv },
      );
      const prs = JSON.parse(listOut.stdout.trim()) as { url: string }[];
      if (prs.length > 0) existingPrUrl = prs[0]!.url;
    } catch (err) {
      const raw = err instanceof Error ? err.message : String(err);
      throw new Error(
        `${cfg.errorTag} Failed to check for existing PRs: ${sanitizeToken(raw, githubToken)}`,
      );
    }

    if (existingPrUrl) {
      return { prUrl: existingPrUrl };
    }

    // No open PR exists — create one.
    let prUrl: string;
    try {
      const createOut = await runGh(
        [
          'pr',
          'create',
          '--repo',
          `${owner}/${repo}`,
          '--head',
          branchName,
          '--base',
          defaultBranch,
          '--title',
          cfg.prTitle(externalId),
          '--body',
          cfg.prBody(externalId, product.product.slug),
        ],
        { env: ghEnv },
      );
      prUrl = createOut.stdout.trim();
    } catch (err) {
      const raw = err instanceof Error ? err.message : String(err);
      throw new Error(`${cfg.errorTag} Failed to create PR: ${sanitizeToken(raw, githubToken)}`);
    }

    return { prUrl };
  } finally {
    // Always clean up the isolated workdir, even on error.
    // Swallow cleanup errors so they never mask the original failure.
    await rm(workDir, { recursive: true, force: true }).catch(() => {});
  }
}

// ── Thin wrappers (backward-compatible) ──────────────────────────────────────

/**
 * Publishes a spec file to the product's knowledge repo as a PR.
 * Wrapper around publishArtifactToPR with kind: 'spec'.
 *
 * @param opts      Publish options including product config, spec path, and token.
 * @param runGit    Injectable git runner (defaults to git via execFile).
 * @param runGh     Injectable gh runner (defaults to gh via execFile).
 */
export async function publishSpecToPR(
  opts: PublishSpecOpts,
  runGit: RunGit = defaultRunGit,
  runGh: RunGh = defaultRunGh,
): Promise<PublishSpecResult> {
  return publishArtifactToPR(
    {
      externalId: opts.externalId,
      product: opts.product,
      artifactPath: opts.specPath,
      githubToken: opts.githubToken,
      kind: 'spec',
    },
    runGit,
    runGh,
  );
}

/**
 * Publishes a plan file to the product's knowledge repo as a PR.
 * Wrapper around publishArtifactToPR with kind: 'plan'.
 *
 * @param opts      Publish options including product config, plan path, and token.
 * @param runGit    Injectable git runner (defaults to git via execFile).
 * @param runGh     Injectable gh runner (defaults to gh via execFile).
 */
export async function publishPlanToPR(
  opts: PublishPlanOpts,
  runGit: RunGit = defaultRunGit,
  runGh: RunGh = defaultRunGh,
): Promise<PublishPlanResult> {
  return publishArtifactToPR(
    {
      externalId: opts.externalId,
      product: opts.product,
      artifactPath: opts.planPath,
      githubToken: opts.githubToken,
      kind: 'plan',
    },
    runGit,
    runGh,
  );
}
