import { ClaudeCodeRuntime, MockAgentRuntime } from '@helm/orchestrator';
import type { IAgentRuntime } from '@helm/orchestrator';
import type { Product } from '@helm/shared';
import { join } from 'node:path';

/**
 * Creates the appropriate IAgentRuntime for the given product's spec-writer
 * specialist configuration.
 *
 * Routing:
 *   'claude_code' → ClaudeCodeRuntime (real Claude Code CLI subprocess)
 *   others        → throws (extend this map as new runtimes are added)
 *
 * The `externalId` and `workdir` parameters are used only by the fallback mock
 * runtime kept here for local development without an ANTHROPIC_API_KEY.
 * Production callers always hit the 'claude_code' branch.
 *
 * Inject this function in tests via vi.mock to avoid spawning the real binary.
 */
export function createRuntimeForProduct(
  product: Product,
  externalId: string,
  workdir: string,
): IAgentRuntime {
  // externalId and workdir are available for runtimes that need them at
  // construction time (e.g. a future LocalFileRuntime). ClaudeCodeRuntime
  // receives them via SpawnParams.workdir/externalId at spawn() time instead.
  void externalId;
  void workdir;

  const runtime = product.specialists.spec_writer.runtime;

  if (runtime === 'claude_code') {
    return new ClaudeCodeRuntime();
  }

  // Unreachable with valid product config today — kept as a safe fallback
  // so a bad config fails loudly rather than silently using the mock.
  throw new Error(
    `[runtime-factory] Unknown specialist runtime: '${runtime}'. ` +
      `Supported values: 'claude_code'.`,
  );
}

/**
 * Returns a MockAgentRuntime pre-configured with side effects that write the
 * spec file the spec-writer handler expects to find on disk.
 *
 * Use this in tests (via vi.mock) and during local development without a real
 * ANTHROPIC_API_KEY.
 */
export function createMockRuntimeForSpec(externalId: string): IAgentRuntime {
  return new MockAgentRuntime({
    messages: [
      {
        role: 'agent',
        content: `[mock] Writing spec for ${externalId}`,
        costUsd: 0,
        timestamp: new Date().toISOString(),
      },
    ],
    sideEffects: async (dir) => {
      const { mkdir, writeFile } = await import('node:fs/promises');
      await mkdir(join(dir, 'specs'), { recursive: true });
      // Use 'wx' (exclusive create) — silently ignore EEXIST on re-dispatch.
      await writeFile(
        join(dir, 'specs', `${externalId}.md`),
        `# ${externalId} — Specification\n\n_Generated by mock specialist._\n`,
        { encoding: 'utf-8', flag: 'wx' },
      ).catch((err: NodeJS.ErrnoException) => {
        if (err.code !== 'EEXIST') throw err;
      });
    },
  });
}
