import { ClaudeCodeRuntime, CodexRuntime, MockAgentRuntime } from '@helm/orchestrator';
import type { IAgentRuntime } from '@helm/orchestrator';
import type { Product } from '@helm/shared';
import { join } from 'node:path';
import { EXTERNAL_ID_REGEX } from './types.js';

/**
 * Creates the appropriate IAgentRuntime for the given product.
 *
 * Routing (driven by the configured runtime):
 *   'claude_code' → ClaudeCodeRuntime (Claude Code CLI subprocess)
 *   'codex'       → CodexRuntime (OpenAI Codex CLI subprocess, see ADR-021)
 *   others        → throws (extend this switch as new runtimes are added)
 *
 * SINGLE-RUNTIME-PER-PRODUCT CONSTRAINT (H1): the dispatcher creates ONE runtime
 * per dispatch and reuses it for every specialist (spec/plan/impl/reviewers/…),
 * so all specialists in a product must share the same runtime. We read
 * `spec_writer.runtime` as the product-wide selector. A per-specialist runtime
 * (e.g. claude_code spec-writer + codex implementer) requires moving runtime
 * creation to per-spawn — deferred to H3.
 *
 * The `externalId` and `workdir` parameters are used only by the fallback mock
 * runtime kept here for local development.
 *
 * Inject this function in tests via vi.mock to avoid spawning the real binary.
 */
export function createRuntimeForProduct(
  product: Product,
  externalId: string,
  workdir: string,
): IAgentRuntime {
  // externalId and workdir are available for runtimes that need them at
  // construction time (e.g. a future LocalFileRuntime). The spawn-based runtimes
  // receive them via SpawnParams.workdir/externalId at spawn() time instead.
  void externalId;
  void workdir;

  // Defense-in-depth for the H1 constraint above: ProductSchema already rejects
  // mixed runtimes (see superRefine in product-schema.ts), but callers that build
  // a Product object without going through schema validation (e.g. unit tests, or
  // a future programmatic config path) would otherwise silently run every stage on
  // spec_writer's runtime. Fail loudly instead.
  const runtimes = new Set(Object.values(product.specialists).map((s) => s.runtime));
  if (runtimes.size > 1) {
    throw new Error(
      `[runtime-factory] ADR-021 H1 violation: all specialists must share one runtime ` +
        `(found: ${[...runtimes].sort().join(', ')}). Per-specialist runtimes are deferred to H3.`,
    );
  }

  const runtime = product.specialists.spec_writer.runtime;

  switch (runtime) {
    case 'claude_code':
      return new ClaudeCodeRuntime();
    case 'codex':
      return new CodexRuntime();
    default:
      // Unreachable with valid product config today — kept as a safe fallback
      // so a bad config fails loudly rather than silently using the mock.
      throw new Error(
        `[runtime-factory] Unknown specialist runtime: '${runtime}'. ` +
          `Supported values: 'claude_code', 'codex'.`,
      );
  }
}

/**
 * Returns a MockAgentRuntime pre-configured with side effects that write the
 * spec file the spec-writer handler expects to find on disk.
 *
 * Use this in tests (via vi.mock) and during local development without a real
 * ANTHROPIC_API_KEY.
 */
export function createMockRuntimeForSpec(externalId: string): IAgentRuntime {
  // Validate before interpolating into a file path — mirrors the guard in
  // dispatch.ts so path traversal is impossible even when this helper is
  // called outside the HTTP layer (e.g. dev scripts or future CLIs).
  if (!EXTERNAL_ID_REGEX.test(externalId) || externalId === '.' || externalId === '..') {
    throw new Error(`[runtime-factory] Invalid externalId for spec path: "${externalId}"`);
  }
  return new MockAgentRuntime({
    messages: [
      {
        role: 'agent',
        content: `[mock] Writing spec for ${externalId}`,
        costUsd: 0,
        timestamp: new Date().toISOString(),
      },
    ],
    sideEffects: async (dir) => {
      const { mkdir, writeFile } = await import('node:fs/promises');
      await mkdir(join(dir, 'specs'), { recursive: true });
      // Use 'wx' (exclusive create) — silently ignore EEXIST on re-dispatch.
      await writeFile(
        join(dir, 'specs', `${externalId}.md`),
        `# ${externalId} — Specification\n\n_Generated by mock specialist._\n`,
        { encoding: 'utf-8', flag: 'wx' },
      ).catch((err: NodeJS.ErrnoException) => {
        if (err.code !== 'EEXIST') throw err;
      });
    },
  });
}
