import { Hono } from 'hono';
import { join } from 'node:path';
import { z } from 'zod';
import { MockAgentRuntime } from '@helm/orchestrator';
import { dispatchStageHandler } from '@helm/orchestrator';
import { getProductRegistry, getItemStore } from '../services/index.js';
import { ItemNotFoundError } from '../services/errors.js';
import { EXTERNAL_ID_REGEX } from '../services/types.js';

export const dispatchRouter = new Hono();

const SlugSchema = z
  .string()
  .min(1)
  .regex(/^[a-z0-9-]+$/);
const BodySchema = z.object({ specialistId: z.string().min(1).optional() }).strict();

dispatchRouter.post('/products/:slug/items/:externalId/dispatch', async (c) => {
  const slug = c.req.param('slug');
  const externalId = c.req.param('externalId');

  if (!SlugSchema.safeParse(slug).success) {
    return c.json({ error: 'Invalid product slug' }, 400);
  }
  if (!EXTERNAL_ID_REGEX.test(externalId)) {
    return c.json({ error: `Invalid externalId: "${externalId}"` }, 400);
  }

  const bodyResult = BodySchema.safeParse(await c.req.json().catch(() => ({})));
  if (!bodyResult.success) {
    return c.json({ error: 'Invalid request body', details: bodyResult.error.issues }, 400);
  }

  // Resolve product
  let product;
  try {
    const products = await getProductRegistry();
    product = products.find((p) => p.product.slug === slug);
    if (!product) return c.json({ error: `Product not found: ${slug}` }, 404);
  } catch (err) {
    console.error('[dispatch] Failed to load product registry:', err);
    return c.json({ error: 'Failed to load product registry' }, 500);
  }

  // Resolve item
  const store = await getItemStore();
  const item = await store.get(externalId);
  if (!item) return c.json({ error: `Item not found: ${externalId}` }, 404);

  // Determine workdir — sibling of the data/items directory
  const envDataDir = process.env.HELM_DATA_DIR?.trim();
  const dataRoot = envDataDir || join(process.cwd(), 'data');
  const workdir = join(dataRoot, 'worktrees', slug, externalId);

  // Build a mock runtime for v0 (Sesión 10 swaps in ClaudeCodeRuntime)
  const runtime = new MockAgentRuntime({
    messages: [
      {
        role: 'agent',
        content: `[mock] Processing ${externalId} for product ${slug}`,
        costUsd: 0,
        timestamp: new Date().toISOString(),
      },
    ],
    sideEffects: async (dir) => {
      const { mkdir, writeFile } = await import('node:fs/promises');
      await mkdir(join(dir, 'specs'), { recursive: true });
      await writeFile(
        join(dir, 'specs', `${externalId}.md`),
        `# ${externalId} — Specification\n\n_Generated by mock specialist._\n`,
        'utf-8',
      );
    },
  });

  try {
    const result = await dispatchStageHandler(
      { externalId, productSlug: item.productSlug, currentStage: item.currentStage },
      product,
      runtime,
      (input) => store.transition(input),
      { workdir, specialistId: bodyResult.data.specialistId },
    );

    if (result.status === 'error' && result.error?.includes('No specialist mapped')) {
      return c.json({ error: result.error }, 400);
    }

    return c.json(result);
  } catch (err) {
    if (err instanceof ItemNotFoundError) {
      return c.json({ error: `Item not found: ${err.externalId}` }, 404);
    }
    console.error('[dispatch] Unexpected error:', err);
    return c.json({ error: 'Dispatch failed' }, 500);
  }
});
